# Generated by Django 4.2.13 on 2024-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_booking_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsdetails',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
