# Generated by Django 4.2.13 on 2024-07-02 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receptionist_booking_room', '0006_remove_cartitems_cart_remove_cartitems_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperCart',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('payment', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='receptionist_booking_room.shoppercart')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_booking_room.roomsdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
