# Generated by Django 4.2.13 on 2024-07-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_booking_room', '0007_shoppercart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Basket',
            new_name='basket',
        ),
    ]
