# Generated by Django 4.2.13 on 2024-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_booking_room', '0009_order_alter_shoppercart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ItemsList',
            field=models.CharField(default=100),
        ),
    ]
