# Generated by Django 4.2.13 on 2024-07-10 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_booking_room', '0011_alter_order_itemslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 8, 48, 34, 887645)),
        ),
    ]
